[build]
  base = "ui/"
  command = "npm install && npm run build"
  publish = "ui/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = ":splat"
  status = 200
  force = true

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
