name: quantum-networking-simulator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipywidgets>=8.0.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - tqdm>=4.62.0
  - pip:
    - qutip==5.0.4
    - plotly>=5.0.0
    - typing-extensions>=4.0.0
