FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
COPY ai_agent/requirements.txt ./ai_agent/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "start.py"]
# CMD ["tail", "-f", "/dev/null"]